### ISSUE TITLE
Include message context in the message body

### ISSUE THREAD

**Issue by adriandiazgar** [WeblateOrg/fedora_messaging#50]
**Describe the solution you'd like**

When a fedora message is generated in weblate the msgctxt field is not included in the message.
Currently the included fields are [ "action", "author" "component", "id", "project", "source", "timestamp", "translation", "url", "user" ]

**Describe alternatives you've considered**

Include a field with the message context (the original, not the one generated by weblate using the msgid concatenated with dots)

**Comment by nijel** [comment]
I didn't notice that part, sorry. Anyway Weblate doesn't have this information at this point (the value is generated when parsing the file and used as it is later).
